version: '3.6'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medium-db
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: username
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5433:80