spring:
  application:
    name: "Medium"
  datasource:
    url: jdbc:postgresql://localhost:5432/medium-db
    driver-class-name: org.postgresql.Driver
    hikari:
      username: postgres
      password: password
      maximum-pool-size: 4
      minimum-idle: 1
      leak-detection-threshold: 5000
      connection-timeout: 5000
      validation-timeout: 5000
      idle-timeout: 60000
      max-life-time: 300000
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        use_sql_comments: true
        format_sql: true
        type:
          descriptor:
            sql: trace
  redis:
    jedis:
      pool:
        max-idle: 150
        min-idle: 50
    timeout: 60000 #connection timeout in milli seconds
management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: always
      show-components: always